const list = [
  
    {
        Id: 1,
        name: "Maxi",
        title: "Maxi",
        description: "Labrador Retriever",
        date: "11 / january/ 2021",
        price: 100,
        category: "",
        sex: "Female",
        Img: './picture/kk.jpg',
    },
    {
        Id: 2,
        title: "Maxa",
        description: "French Bulldog",
        date: "11 / january/ 2021",
        price: 300,
        category: "",
        status: "",
        Img: './picture/beagle.jpg',
    },
    {
        Id: 3,
        title: "Mingo",
        description: "Golden Retriever",
        date: "11 / january/ 2021",
        price: 400,
        category: "",
        status: "",
        Img: './picture/golden_retriever.jpg',
    },
    {
        Id: 4,
        title: "Ponny",
        description: "German Shepherd ",
        date: "11 / january/ 2021",
        price: 500,
        category: "",
        status: "",
        Img: './picture/german_shepherd.jpg'
    },
    {
        Id: 5,
        title: "Cooper",
        description: " Bulldog",
        date: "11/May/2021",
        price: 600,
        category: "",
        status: "",
        Img: './picture/bulldog.jpg',
    },
    {
        Id: 6,
        title: "Milla",
        description: "Rottweiler",
        date: "11 / january/ 2021",
        price: 700,
        category: "",
        status: "",
        Img: './picture/rottweiler.jpg',
    },
    {
        Id: 7,
        title: "Rocky",
        description: "Poodle",
        date: "11 / january/ 2021",
        price: 800,
        category: "",
        status: "",
        Img: "./picture/poodle.jpg",
    },
    {
        Id: 8,
        title: "Charlie",
        description: "German Shorthaired Pointer",
        date: "11/May/2021",
        price: 900,
        category: "",
        status: "",
        Img: './picture/french_bulldog.jpg',
    },
    {
        Id: 9,
        title: "Zoe",
        description: "Beagle",
        date: "11/May/2021",
        price: 1500,
        category: "",
        status: "",
        Img: './picture/beagle.jpg',
    }
]



export default list